import type { PlatformVendor } from "./types"

export const platformPortfolioDemo: PlatformVendor[] = [
  {
    id: "demo-alrabee",
    name: "أزياء الربيع",
    handle: "alrabee-fashion",
    status: "active",
    contact_email: "sara@alrabee.com",
    primary_color: "#9f74ff",
    created_at: "2025-01-12T09:00:00.000Z",
    updated_at: "2026-07-15T10:24:00.000Z",
    product_count: 48,
    metadata: { deployment_version: "v1.8.3" },
    domains: [
      { id: "domain-1", domain: "alrabee-fashion.com", is_primary: true },
      { id: "domain-2", domain: "shop.alrabee-fashion.com", is_primary: false },
      { id: "domain-3", domain: "sale.alrabee-fashion.com", is_primary: false },
    ],
    members: [
      { id: "member-1", email: "sara@alrabee.com", role: "owner", status: "active" },
      { id: "member-2", email: "ops@alrabee.com", role: "admin", status: "active" },
      { id: "member-3", email: "catalog@alrabee.com", role: "member", status: "active" },
      { id: "member-4", email: "orders@alrabee.com", role: "member", status: "active" },
      { id: "member-5", email: "finance@alrabee.com", role: "member", status: "active" },
    ],
    provisioning: {
      id: "provisioning-1",
      status: "completed",
      requested_handle: "alrabee-fashion",
      requested_domain: "alrabee-fashion.com",
      requested_owner_email: "sara@alrabee.com",
      requested_plan_code: "professional_commerce",
      created_at: "2025-01-12T09:00:00.000Z",
      completed_at: "2025-01-12T09:12:00.000Z",
    },
  },
  {
    id: "demo-future",
    name: "إلكترونيات المستقبل",
    handle: "future-electronics",
    status: "active",
    contact_email: "admin@future-elec.com",
    primary_color: "#3489ff",
    created_at: "2025-08-03T08:00:00.000Z",
    updated_at: "2026-07-13T08:20:00.000Z",
    product_count: 31,
    metadata: { deployment_version: "v2.2.1" },
    domains: [{ id: "domain-4", domain: "future-elec.com", is_primary: true }],
    members: [
      { id: "member-6", email: "admin@future-elec.com", role: "owner", status: "active" },
      { id: "member-7", email: "ops@future-elec.com", role: "member", status: "active" },
      { id: "member-8", email: "sales@future-elec.com", role: "member", status: "active" },
      { id: "member-9", email: "stock@future-elec.com", role: "member", status: "active" },
    ],
    provisioning: {
      id: "provisioning-2",
      status: "completed",
      requested_plan_code: "professional_commerce",
      completed_at: "2025-08-03T08:16:00.000Z",
    },
  },
  {
    id: "demo-perfume",
    name: "بيت العطور",
    handle: "perfume-home",
    status: "active",
    contact_email: "owner@perfumehome.sa",
    primary_color: "#8d62d9",
    created_at: "2026-01-10T12:00:00.000Z",
    updated_at: "2026-07-09T13:07:00.000Z",
    product_count: 18,
    metadata: { deployment_version: "v1.3.7" },
    domains: [{ id: "domain-5", domain: "perfumehome.sa", is_primary: true }],
    members: [
      { id: "member-10", email: "owner@perfumehome.sa", role: "owner", status: "active" },
      { id: "member-11", email: "team@perfumehome.sa", role: "member", status: "active" },
    ],
    provisioning: {
      id: "provisioning-3",
      status: "completed",
      requested_plan_code: "starter_whatsapp",
      completed_at: "2026-01-10T12:14:00.000Z",
    },
  },
  {
    id: "demo-baby",
    name: "مستلزمات الطفل",
    handle: "baby-needs",
    status: "draft",
    contact_email: "hello@babyneeds.com",
    primary_color: "#ff5f82",
    created_at: "2026-06-15T11:00:00.000Z",
    updated_at: "2026-07-07T09:40:00.000Z",
    product_count: 7,
    metadata: { deployment_version: "v0.9.4" },
    domains: [{ id: "domain-6", domain: "babyneeds.com", is_primary: true }],
    members: [{ id: "member-12", email: "hello@babyneeds.com", role: "owner", status: "active" }],
    provisioning: {
      id: "provisioning-4",
      status: "completed",
      requested_plan_code: "starter_whatsapp",
      completed_at: "2026-06-15T11:11:00.000Z",
    },
  },
  {
    id: "demo-chef",
    name: "مطبخ الشيف",
    handle: "chef-kitchen",
    status: "suspended",
    contact_email: "info@chefkitchen.com",
    primary_color: "#f0a538",
    created_at: "2025-10-22T11:00:00.000Z",
    updated_at: "2026-07-05T08:15:00.000Z",
    product_count: 22,
    metadata: { deployment_version: "v1.6.2" },
    domains: [{ id: "domain-7", domain: "chefkitchen.com", is_primary: true }],
    members: [
      { id: "member-13", email: "info@chefkitchen.com", role: "owner", status: "active" },
      { id: "member-14", email: "team@chefkitchen.com", role: "member", status: "active" },
      { id: "member-15", email: "orders@chefkitchen.com", role: "member", status: "active" },
    ],
    provisioning: {
      id: "provisioning-5",
      status: "completed",
      requested_plan_code: "professional_commerce",
      completed_at: "2025-10-22T11:16:00.000Z",
    },
  },
  {
    id: "demo-active",
    name: "رياضة ونشاط",
    handle: "active-sport",
    status: "active",
    contact_email: "owner@active-sport.com",
    primary_color: "#44d575",
    created_at: "2025-12-01T11:00:00.000Z",
    updated_at: "2026-06-30T10:00:00.000Z",
    product_count: 35,
    metadata: { deployment_version: "v1.4.0" },
    domains: [{ id: "domain-8", domain: "active-sport.com", is_primary: true }],
    members: [
      { id: "member-16", email: "owner@active-sport.com", role: "owner", status: "active" },
      { id: "member-17", email: "ops@active-sport.com", role: "member", status: "active" },
      { id: "member-18", email: "sales@active-sport.com", role: "member", status: "active" },
      { id: "member-19", email: "stock@active-sport.com", role: "member", status: "active" },
    ],
    provisioning: {
      id: "provisioning-6",
      status: "completed",
      requested_plan_code: "professional_commerce",
      completed_at: "2025-12-01T11:13:00.000Z",
    },
  },
]

