import {
  ArrowLeft,
  BuildingStorefront,
  Globe,
  Loader,
  MagnifyingGlass,
  ShieldCheck,
} from "@medusajs/icons"
import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react"

import { getPlatformStorefrontPreview, listPlatformStorefrontTemplates } from "../api"
import { draftCatalog, type CreationValues } from "../creation-drafts"
import type {
  PlatformStorefrontPreview,
  PlatformStorefrontPreviewProduct,
  PlatformStorefrontTemplateKey,
} from "../types"
import {
  createStorefrontTemplatePreview,
  type StorefrontTemplatePreviewModel,
} from "../storefront-template-preview-data"
import { visualPreviewQuery, isAdminVisualPreviewEnabled } from "../visual-preview"
import {
  resolveStorefrontPreviewOrigin,
  buildStorefrontEditorPreviewProfile,
  STOREFRONT_EDITOR_PREVIEW_MESSAGE,
  STOREFRONT_EDITOR_PREVIEW_READY_MESSAGE,
  type StorefrontEditorPreviewMessage,
  type StorefrontEditorPreviewProfile,
} from "../storefront-editor-preview"
import "./storefront-preview.css"
import { urbxHomeDefaults, urbxShopDefaults } from "../urbx-home-defaults"
import { urbxPreviewProducts } from "../../../../storefront/src/templates/urbx/urbx-preview-data"
import { template6PreviewProducts } from "../../../../storefront/src/templates/template-6/template-6-preview-data"

type StorefrontPreviewPageProps =
  | { storeProfileId: string; templateKey?: never }
  | { storeProfileId?: never; templateKey: PlatformStorefrontTemplateKey }

const fallbackPrimary = "#1455e6"
const fallbackSecondary = "#55b8ff"

const safeColor = (value: string | null, fallback: string) =>
  value && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback

const copyByLocale = {
  "ar-LY": {
    home: "الرئيسية", products: "المنتجات", contact: "تواصل معنا",
    search: "ابحث في المنتجات", welcome: "مرحباً بك في", title: "اكتشف تشكيلتنا",
    description: "واجهة بسيطة وواضحة تبرز منتجات المتجر وهويته الخاصة.",
    browse: "تصفح المنتجات", features: ["تجربة عربية", "تصميم متجاوب", "هوية مستقلة"],
    selections: "مختارات المتجر", featured: "منتجات مميزة", clear: "مسح البحث",
    noResults: "لا توجد نتائج مطابقة", empty: "المتجر جاهز لاستقبال أول منتج",
    noContact: "بيانات التواصل لم تُضف بعد", generated: "واجهة أساسية مُنشأة بواسطة LabibTech",
  },
  "en-LY": {
    home: "Home", products: "Products", contact: "Contact",
    search: "Search products", welcome: "Welcome to", title: "Discover our collection",
    description: "A clear storefront that brings the Store's products and identity forward.",
    browse: "Browse products", features: ["English experience", "Responsive design", "Independent identity"],
    selections: "Store selections", featured: "Featured products", clear: "Clear search",
    noResults: "No matching products", empty: "This Store is ready for its first product",
    noContact: "Contact details have not been added yet", generated: "Storefront generated by LabibTech",
  },
} as const

const formatMoney = (amount: number, locale: "ar-LY" | "en-LY") =>
  new Intl.NumberFormat(locale, {
    style: "currency",
    currency: "LYD",
    currencyDisplay: "code",
  }).format(amount)

const productInitial = (product: PlatformStorefrontPreviewProduct) =>
  product.title.trim().charAt(0) || "م"

const localized = (value: string) => ({ ar: value, en: value })

export function templateRuntimeProfile(templateKey: PlatformStorefrontTemplateKey): StorefrontEditorPreviewProfile {
  const preview = createStorefrontTemplatePreview(templateKey)
  const heroImage = templateKey === "standard"
    ? "/assets/standard/desktop-hero-editorial.webp"
    : templateKey === "glow-beauty"
      ? "/assets/glow-beauty/hero-beauty-collection.png"
      : preview.hero.image_url.startsWith("/assets/admin/") ? null : preview.hero.image_url
  const categoryNames = templateKey === "urbx" ? ["Hoodies", "T-Shirts", "Bottoms", "Accessories"] : templateKey === "glow-beauty"
    ? ["Skincare", "Makeup", "Fragrance", "Haircare", "Tools"]
    : ["Handbags", "Watches", "Sunglasses", "Shoes", "Dresses", "Casual"]
  const categoryImages = templateKey === "urbx" ? ["hoodies", "tshirts", "bottoms", "accessories"].map(key => `/assets/urbx/category-${key}-v1.png`) : templateKey === "glow-beauty"
    ? [
        "/assets/glow-beauty/product-radiance-serum.png",
        "/assets/glow-beauty/product-matte-lipstick.png",
        "/assets/glow-beauty/category-fragrance.png",
        "/assets/glow-beauty/category-haircare.png",
        "/assets/glow-beauty/category-tools.png",
      ]
    : []

  return {
    name: preview.name,
    handle: preview.handle,
    domain: preview.domain,
    locale: preview.locale === "en-LY" ? "en-LY" : "ar-LY",
    contact: preview.contact,
    branding: {
      logo_url: templateKey === "glow-beauty"
        ? "/assets/glow-beauty/glow-petal-mark-v1.png"
        : preview.branding.logo_url,
      primary_color: preview.branding.primary_color,
      secondary_color: preview.branding.secondary_color,
      typography_key: "cairo",
    },
    storefront: {
      schema_version: 1,
      template_key: templateKey,
      content: {
        ...(templateKey === "urbx" ? { home: urbxHomeDefaults, shop: urbxShopDefaults } : {}),
        navigation: {
          items: [
            { key: "home", label: { ar: "الرئيسية", en: "Home" }, enabled: true },
            { key: "categories", label: { ar: "التصنيفات", en: "Categories" }, enabled: true },
            { key: "favorites", label: { ar: "المفضلة", en: "Saved" }, enabled: true },
            { key: "cart", label: { ar: "السلة", en: "Cart" }, enabled: true },
            { key: "account", label: { ar: "الحساب", en: "Account" }, enabled: true },
            { key: "orders", label: { ar: "الطلبات", en: "Orders" }, enabled: false },
            { key: "settings", label: { ar: "الإعدادات", en: "Settings" }, enabled: false },
          ],
        },
        hero: {
          eyebrow: localized(preview.hero.eyebrow || "New arrivals"),
          heading: localized(preview.hero.heading),
          subheading: localized(preview.hero.subheading),
          cta_label: localized(preview.hero.cta_label),
          cta_target: "catalog",
          image_url: heroImage,
          slides: heroImage ? [{ id: "template-preview-hero", image_url: heroImage, alt: localized(preview.hero.heading), enabled: true }] : [],
          buttons: [{ id: "template-preview-shop", label: localized(preview.hero.cta_label), href: "/products", background_color: preview.branding.primary_color ?? fallbackPrimary, text_color: "#ffffff", style: "solid", enabled: true }],
          benefits: [
            { id: "template-preview-delivery", icon: "truck", title: { ar: "خيارات توصيل", en: "Delivery options" }, subtitle: { ar: "تظهر عند الدفع", en: "Shown at checkout" } },
            { id: "template-preview-returns", icon: "package", title: { ar: "سياسة الاسترجاع", en: "Returns policy" }, subtitle: { ar: "راجع سياسة المتجر", en: "See Store policy" } },
            { id: "template-preview-payment", icon: "shield", title: { ar: "دفع آمن", en: "Secure payment" }, subtitle: { ar: "خيارات دفع المتجر", en: "Store payment options" } },
          ],
        },
        brands: {
          heading: { ar: "تسوق حسب التصنيف", en: "Shop by category" },
          subheading: { ar: "اكتشف مختارات المتجر", en: "Explore the Store selection" },
          items: categoryNames.map((name, index) => ({ id: `template-preview-brand-${index}`, name: localized(name), slug: name.toLocaleLowerCase().replace(/\s+/g, "-"), image_url: categoryImages[index] ?? null })),
        },
        about: { title: { ar: "أناقة يومية", en: "Everyday style" }, body: localized(preview.hero.subheading) },
        contact: { heading: { ar: "تواصل معنا", en: "Contact us" }, body: { ar: "فريق المتجر متاح للمساعدة.", en: "The Store team is available to help." } },
        policies: {
          delivery: { title: { ar: "سياسة التوصيل", en: "Delivery policy" }, body: { ar: "تحدد عند إعداد المتجر.", en: "Configured for each Store." } },
          returns: { title: { ar: "سياسة الاسترجاع", en: "Returns policy" }, body: { ar: "تحدد عند إعداد المتجر.", en: "Configured for each Store." } },
          privacy: { title: { ar: "سياسة الخصوصية", en: "Privacy policy" }, body: { ar: "تحدد عند إعداد المتجر.", en: "Configured for each Store." } },
          terms: { title: { ar: "الشروط والأحكام", en: "Terms and conditions" }, body: { ar: "تحدد عند إعداد المتجر.", en: "Configured for each Store." } },
        },
      },
    },
  }
}

export function templateRuntimeCatalog(
  templateKey: PlatformStorefrontTemplateKey,
): PlatformStorefrontPreviewProduct[] {
  const preview = createStorefrontTemplatePreview(templateKey)
  const glowMeta: Record<
    string,
    { subtitle: string; category: string; badge?: string; compare?: number }
  > = {
    "radiance-serum": { subtitle: "Brightening & Glow", category: "Skincare", badge: "BEST SELLER", compare: 160 },
    "hydra-moisturizer": { subtitle: "24H Hydration", category: "Skincare", badge: "NEW" },
    "matte-lipstick": { subtitle: "Long Lasting Color", category: "Makeup", compare: 95 },
    "rose-eau-de-parfum": { subtitle: "Elegant Floral Scent", category: "Fragrance" },
    "glow-foundation": { subtitle: "Natural Finish", category: "Makeup" },
    "luxe-face-cream": { subtitle: "Deep Nourishment", category: "Skincare" },
  }

  // Studio-only catalog: never installed in or merged with an existing Store.
  const products = templateKey === "urbx" ? urbxPreviewProducts : templateKey === "template-6" ? template6PreviewProducts : preview.products
  return products.map((product) => {
    const meta = product.handle ? glowMeta[product.handle] : undefined
    const unitPrice = product.price_lyd ?? 0
    return {
      ...product,
      subtitle: meta?.subtitle ?? null,
      image_urls: product.thumbnail_url ? [product.thumbnail_url] : [],
      compare_at_price_lyd: meta?.compare ?? null,
      category: "category" in product && typeof product.category === "string" ? product.category : meta?.category ?? null,
      badge: meta?.badge ?? null,
      options: [{ name: "size", values: ["Standard"] }],
      variants: [{
        id: `template-preview:${product.handle ?? "product"}`,
        title: "Standard",
        options: { size: "Standard" },
        unit_price: unitPrice,
        available_for_sale: true,
      }],
    }
  })
}

function TemplateRuntimePreview({ templateKey }: { templateKey: PlatformStorefrontTemplateKey }) {
  const frameRef = useRef<HTMLIFrameElement>(null)
  const channelRef = useRef(globalThis.crypto?.randomUUID?.() ?? `${Date.now().toString(36)}-template-preview`)
  const previewOrigin = useMemo(() => resolveStorefrontPreviewOrigin(import.meta.env.VITE_STOREFRONT_PREVIEW_ORIGIN, import.meta.env.DEV), [])
  const [values, setValues] = useState<CreationValues | null>(null)
  const [failed, setFailed] = useState(false)
  const [retry, setRetry] = useState(0)
  const isDemo = isAdminVisualPreviewEnabled()
  const locale: "en-LY" | "ar-LY" = new URLSearchParams(window.location.search).get("locale") === "ar-LY" ? "ar-LY" : "en-LY"
  useEffect(() => {
    if (isDemo) return
    const controller = new AbortController()
    setValues(null); setFailed(false)
    void listPlatformStorefrontTemplates(controller.signal).then(result => {
      if (controller.signal.aborted) return
      const next = result.creation_previews?.[templateKey]
      if (!next) throw new Error("Template preview is unavailable.")
      setValues(next)
    }).catch(() => { if (!controller.signal.aborted) setFailed(true) })
    return () => controller.abort()
  }, [isDemo, templateKey, retry])
  const profile = useMemo(() => values ? buildStorefrontEditorPreviewProfile(
    { handle: "template-preview", domains: [] },
    { ...values.configuration, locale }, values.document,
  ) : isDemo ? { ...templateRuntimeProfile(templateKey), locale } : null, [values, locale, isDemo, templateKey])
  const catalog = useMemo(() => values ? draftCatalog(values, "template-preview") : isDemo ? templateRuntimeCatalog(templateKey) : [], [values, isDemo, templateKey])
  const previewUrl = useMemo(() => {
    if (!previewOrigin || !profile) return null
    const url = new URL(previewOrigin)
    url.searchParams.set("editor-preview", "1")
    url.searchParams.set("template", templateKey)
    url.searchParams.set("locale", profile.locale)
    url.searchParams.set("channel", channelRef.current)
    return url.toString()
  }, [previewOrigin, profile?.locale, templateKey])
  const sendProfile = useCallback(() => {
    if (!previewOrigin || !profile || !frameRef.current?.contentWindow) return
    const message: StorefrontEditorPreviewMessage = {
      type: STOREFRONT_EDITOR_PREVIEW_MESSAGE,
      version: 1,
      channel: channelRef.current,
      profile,
      catalog,
      commerce_available: false,
    }
    frameRef.current.contentWindow.postMessage(message, previewOrigin)
  }, [catalog, previewOrigin, profile])

  useEffect(() => {
    if (!previewOrigin) return
    const receive = (event: MessageEvent<unknown>) => {
      if (event.origin !== previewOrigin || event.source !== frameRef.current?.contentWindow || !event.data || typeof event.data !== "object") return
      const message = event.data as Record<string, unknown>
      if (message.type === STOREFRONT_EDITOR_PREVIEW_READY_MESSAGE && message.version === 1 && message.channel === channelRef.current) sendProfile()
    }
    window.addEventListener("message", receive)
    return () => window.removeEventListener("message", receive)
  }, [previewOrigin, sendProfile])

  if (!profile && previewOrigin) return <main className="owner-storefront-preview-state"><div><h1>{failed ? "Template preview is unavailable" : "Loading the exact store design…"}</h1>{failed ? <button onClick={() => setRetry(value => value + 1)}>Try again</button> : null}<a href={`/dashboard/storefronts${visualPreviewQuery()}`}>Back to Templates Studio</a></div></main>
  if (!previewUrl || !profile) {
    return <main className="owner-storefront-preview-state"><div><BuildingStorefront /><h1>Real storefront preview is not configured</h1><p>Configure the customer Storefront origin for this environment.</p><a href={`/dashboard/storefronts${visualPreviewQuery()}`}>Back to Templates Studio</a></div></main>
  }

  return <div className="owner-template-runtime-preview">
    <div className="store-preview-adminbar"><div><ShieldCheck /><span><strong>Real template renderer</strong> — browse the same storefront code assigned to a Store.</span></div><a href={`/dashboard/storefronts${visualPreviewQuery()}`}><ArrowLeft /> Back to Templates Studio</a></div>
    <iframe ref={frameRef} src={previewUrl} title={`${profile.name} complete storefront preview`} />
  </div>
}

export function StorefrontPreviewPage(props: StorefrontPreviewPageProps) {
  if (props.templateKey) return <TemplateRuntimePreview templateKey={props.templateKey} />
  return <StoreProfilePreviewPage storeProfileId={props.storeProfileId} />
}

function StoreProfilePreviewPage({ storeProfileId }: { storeProfileId: string }) {
  const [storefront, setStorefront] = useState<PlatformStorefrontPreview | StorefrontTemplatePreviewModel | null>(null)
  const [status, setStatus] = useState<"loading" | "ready" | "error">("loading")
  const [query, setQuery] = useState("")
  const [retryToken, setRetryToken] = useState(0)

  useEffect(() => {
    if (!storeProfileId) return
    const controller = new AbortController()
    setStatus("loading")
    setStorefront(null)

    getPlatformStorefrontPreview(storeProfileId)
      .then((result) => {
        if (controller.signal.aborted) return
        setStorefront(result)
        setStatus("ready")
        document.title = `معاينة ${result.name} | LabibTech`
      })
      .catch(() => {
        if (controller.signal.aborted) return
        setStatus("error")
        document.title = "معاينة المتجر | LabibTech"
      })

    return () => controller.abort()
  }, [retryToken, storeProfileId])

  const visibleProducts = useMemo(() => {
    if (!storefront) return []
    const normalized = query.trim().toLocaleLowerCase("ar")
    if (!normalized) return storefront.products
    return storefront.products.filter((product) =>
      `${product.title} ${product.description ?? ""}`
        .toLocaleLowerCase("ar")
        .includes(normalized),
    )
  }, [query, storefront])

  if (status !== "ready" || !storefront) {
    return (
      <main className="owner-storefront-preview-state" dir="rtl">
        <div>
          {status === "loading" ? <Loader className="spin" /> : <BuildingStorefront />}
          <h1>{status === "loading" ? "جارٍ تجهيز معاينة المتجر" : "تعذّر فتح المعاينة"}</h1>
          <p>
            {status === "loading"
              ? "نحمّل الهوية والمنتجات من السجل الدائم للمتجر."
              : "تحقق من أن المتجر ما زال نشطاً ثم أعد المحاولة."}
          </p>
          {status === "error" ? (
            <button type="button" onClick={() => setRetryToken((value) => value + 1)}>
              إعادة المحاولة
            </button>
          ) : null}
          <a href={`/dashboard/clients${visualPreviewQuery()}`}>العودة إلى لوحة الإدارة</a>
        </div>
      </main>
    )
  }

  const primary = safeColor(storefront.branding.primary_color, fallbackPrimary)
  const secondary = safeColor(storefront.branding.secondary_color, fallbackSecondary)
  const locale = storefront.locale === "en-LY" ? "en-LY" : "ar-LY"
  const direction = locale === "en-LY" ? "ltr" : "rtl"
  const copy = copyByLocale[locale]
  const style = {
    "--store-preview-primary": primary,
    "--store-preview-secondary": secondary,
    "--store-preview-font": '"Cairo Variable", "Cairo", sans-serif',
  } as CSSProperties
  const contact =
    storefront.contact.whatsapp_number ||
    storefront.contact.public_phone ||
    storefront.contact.public_email
  const mockStorefront = "is_mock" in storefront ? storefront : null
  const hero = mockStorefront?.hero
  const previewClassName = mockStorefront
    ? `owner-storefront-preview owner-storefront-preview--${mockStorefront.template_key}${mockStorefront.template_key === "luxe-commerce-full" ? " owner-storefront-preview--luxe-commerce" : ""}`
    : "owner-storefront-preview"
  const backPath = `${mockStorefront ? "/dashboard/storefronts" : "/dashboard/clients"}${visualPreviewQuery()}`

  return (
    <div className={previewClassName} style={style} dir={direction} lang={locale}>
      <a className="store-preview-skip" href="#store-preview-main">تجاوز إلى المحتوى</a>

      <div className="store-preview-adminbar">
        <div>
          <ShieldCheck />
          <span>
            <strong>{mockStorefront ? "Mock template preview" : "معاينة خاصة بالإدارة"}</strong>
            {mockStorefront
              ? " — Explore the complete design before creating a Store. Nothing here is saved."
              : " — هذه الواجهة تُبنى تلقائياً من هوية المتجر الحقيقية."}
          </span>
        </div>
        <a href={backPath}><ArrowLeft /> {mockStorefront ? "Back to Templates Studio" : "العودة إلى لوحة الإدارة"}</a>
      </div>

      <header className="store-preview-header">
        <div className="store-preview-shell store-preview-header__inner">
          <a className="store-preview-brand" href="#store-preview-main" aria-label={`${storefront.name} - الرئيسية`}>
            <BrandVisual storefront={storefront} />
            <span>
              <strong>{storefront.name}</strong>
              <small dir="ltr">{storefront.domain || storefront.handle}</small>
            </span>
          </a>

          <nav aria-label="التنقل في معاينة المتجر">
            <a href="#store-preview-main">{copy.home}</a>
            <a href="#store-preview-products">{copy.products}</a>
            <a href="#store-preview-contact">{copy.contact}</a>
          </nav>

          <label className="store-preview-search">
            <MagnifyingGlass />
            <input
              type="search"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder={copy.search}
              aria-label={copy.search}
            />
          </label>
        </div>
      </header>

      <main id="store-preview-main">
        <section className="store-preview-hero" aria-labelledby="store-preview-title">
          <div className="store-preview-shell store-preview-hero__inner">
            <div className="store-preview-hero__copy">
              <span>{hero?.eyebrow ?? `${copy.welcome} ${storefront.name}`}</span>
              <h1 id="store-preview-title">{hero?.heading ?? copy.title}</h1>
              <p>{hero?.subheading ?? copy.description}</p>
              <a className="store-preview-primary-action" href="#store-preview-products">
                {hero?.cta_label ?? copy.browse} <ArrowLeft />
              </a>
              <ul aria-label="مزايا واجهة المتجر">
                {copy.features.map((feature) => <li key={feature}>{feature}</li>)}
              </ul>
            </div>
            <div className="store-preview-hero__visual" aria-hidden="true">
              {hero?.image_url ? (
                <img className="store-preview-hero__image" src={hero.image_url} alt="" />
              ) : (
                <>
                  <div className="store-preview-hero__halo" />
                  <BrandVisual storefront={storefront} large />
                  <span className="store-preview-orbit store-preview-orbit--one" />
                  <span className="store-preview-orbit store-preview-orbit--two" />
                </>
              )}
            </div>
          </div>
        </section>

        <section id="store-preview-products" className="store-preview-products store-preview-shell" aria-labelledby="store-preview-products-title">
          <div className="store-preview-section-heading">
            <div>
              <span>{copy.selections}</span>
              <h2 id="store-preview-products-title">{copy.featured}</h2>
              <p>{storefront.product_count ? storefront.product_count.toLocaleString(locale) : copy.empty}</p>
            </div>
            {query ? <button type="button" onClick={() => setQuery("")}>{copy.clear}</button> : null}
          </div>

          {visibleProducts.length ? (
            <div className="store-preview-product-grid">
              {visibleProducts.map((product) => (
                <article key={product.handle || product.title} className="store-preview-product-card">
                  <div className="store-preview-product-card__media">
                    {product.thumbnail_url ? <img src={product.thumbnail_url} alt={product.title} /> : <span>{productInitial(product)}</span>}
                  </div>
                  <div>
                    <h3>{product.title}</h3>
                    <p>{product.description || "تفاصيل المنتج ستظهر هنا عند إضافتها."}</p>
                    {product.price_lyd !== null ? <strong>{formatMoney(product.price_lyd, locale)}</strong> : null}
                  </div>
                </article>
              ))}
            </div>
          ) : (
            <div className="store-preview-empty">
              <BuildingStorefront />
              <h3>{query ? copy.noResults : copy.empty}</h3>
              <p>{query ? "جرّب عبارة بحث مختلفة أو امسح البحث." : "أضف المنتجات وانشرها من لوحة البائع لتظهر تلقائياً في هذه الواجهة."}</p>
              {query ? <button type="button" onClick={() => setQuery("")}>عرض كل المنتجات</button> : null}
            </div>
          )}
        </section>
      </main>

      <footer id="store-preview-contact" className="store-preview-footer">
        <div className="store-preview-shell store-preview-footer__inner">
          <div className="store-preview-footer__brand"><BrandVisual storefront={storefront} /><strong>{storefront.name}</strong></div>
          <div>
            <Globe />
            <span dir="ltr">{storefront.domain || storefront.handle}</span>
          </div>
          <div>
            {contact ? <span dir="ltr">{contact}</span> : <span>{copy.noContact}</span>}
          </div>
          <p>{copy.generated}</p>
        </div>
      </footer>
    </div>
  )
}

function BrandVisual({ storefront, large = false }: { storefront: PlatformStorefrontPreview; large?: boolean }) {
  return (
    <span className={`store-preview-brand-visual${large ? " is-large" : ""}`}>
      {storefront.branding.logo_url ? (
        <img src={storefront.branding.logo_url} alt="" />
      ) : (
        <span>{storefront.name.trim().charAt(0) || "م"}</span>
      )}
    </span>
  )
}
